### ISSUE TITLE
Dploy only uploads the .rev file

### ISSUE THREAD

**Issue by felds** [LeanMeanFightingMachine/dploy#19]
No other files are touched.

### Config

```yaml
dev:
    scheme: sftp
    # port: 21
    host: •••••••••••
    user: •••••••••••
    pass: •••••••••••
    check: true
    path:
        local: /www/clients/•••••••••••/hotsite/
        remote: /home/•••••••••••/www/hotsite/
```

### Output

```text
Connecting to dev...
Checking revisions...
Checking diffs...
Files that will be uploaded:
[ ? ] /www/clients/•••••••••/hotsites/.rev
Question: Are you sure you want to upload those files? (y/n):  y
[ + ] File uploaded: /www/clients/•••••••••/hotsites/.rev:
Upload completed for dev
All Completed :)
```

### Diff

```diff
commit 49d2e1e2956e0142d317efabb5e2257b0a204c25
Author: •••••••••••••••••••
Date:   Wed Nov 20 17:11:21 2013 -0200

    hello dploy

diff --git a/index.html b/index.html
new file mode 100644
index 0000000..ddbe00a
--- /dev/null
+++ b/test.html
@@ -0,0 +1,2 @@
+<h1>Hello World!</h1>
+
```

um grande abraço!

**Comment by Ouadie** [comment]
Same problem here as @oskarrough

**Comment by SpireonPleasure** [comment]
I too am wondering if .rev should be in the gitignore file.

**Comment by robertoswald** [comment]
dploy is looking at your commit log history to see what files it needs to upload. Unless you are committing files dploy will not pick up the files that are changing.

as for the .rev file. This file gets created when you start dploy, then it gets uploaded and once complete gets removed locally so you don't need to add it to the .gitignore or anything like that. I have found if I start a dploy and during the check I cancel it the .rev file stays behind but it is safe at this point to just remove it.

**Comment by patricknelson** [comment]
Bump. I just installed `dploy` after having used it years ago with it working fine and have now stumbled across this bug. I'm running v1.2.0. I've got many hundreds of changed files, but this is the output I end up getting:

```
Connecting to stage...
Checking revisions...
Checking diffs between [f4c7c9d26ee799c0e01afc1f6f84fc12b20563b0] > [4bf0c3c81e2649401ddc06f44ae03d767ad89741]
Files that will be uploaded:
[ ? ] ./.rev > /web/content/.rev
```

How can this be fixed? Is there a version of dploy that I can revert to that works?

**Comment by oller** [comment]
`dploy` needs the files to be under git source control @patricknelson, so it can perform the diffs, I'd make sure you've not referenced the files you want to upload in `.gitignore` and check they're under source control.

**Comment by patricknelson** [comment]
@oller I understand, that wasn't the issue. I dug into the code of DPLOY and found here https://github.com/LeanMeanFightingMachine/dploy/blob/master/src/deploy.coffee#L362 that it was not properly comparing my local relative path (which I had configured below) with the paths found in the git index and, because my local path was setup incorrectly (or at least wasn't found inside that git path) it was not working.

So this was my path configuration:

```yaml
stage:
    host: "ftp.server.com"
    scheme: "sftp"
    user: "username"
    # Password intentionally excluded; will prompt instead.
    path:
        local: "./"
        remote: "/web/content/"
    exclude: ["dploy.yaml"]
    check: true
```

So apparently, that local path used to work, but now it does not. The solution for me was to simply remove that `local` reference and all is well again. This may help anyone else with a similar issue. Maybe this issue was affecting the person above? Since it was doing a direct comparison to the output from `git diff --name-status`, my file in the index would always be relative, e.g. `directory/file.js`) while the user has setup a full path prefix to the file, which will NOT exist in that output from `git diff`.

Thanks though!
