### ISSUE TITLE
Set paths for multiple sub-directories?

### ISSUE THREAD

**Issue by charlievaughan** [LeanMeanFightingMachine/dploy#80]
What I would like to do is specify multiple sub-directories to deploy to something like this: 
<pre><code>
path:
     local: 'app/design/frontend'
     remote: '/mydomain.com/html/app/design/frontend'
path:
     local: 'media'
     remote: '/mydomain.com/html/media'
path:
     local: 'skin/frontend'
     remote: '/mydomain.com/html/skin/frontend'
</code></pre>

Although I originally thought this worked, I now realise only the last path works as each subsequent path specified overrides the last.

**Comment by labo-css** [comment]
I'm interested too if this is possible. Any ideas?

**Comment by diessica** [comment]
It'd be cool for sure :)

Meanwhile,  you can use [Multiple Environments](https://github.com/LeanMeanFightingMachine/dploy#multiple-environments).

```
thing1:
    [...]
    path:
        local: "deploy1/"
        remote: "public_html/"

thing2:
   [...]
    path:
        local: "deploy2/"
        remote: "public_html/"

thing3:
    [...]
    path:
        local: "deploy3/"
        remote: "public_html/"
```

And deploy it like this:
```
dploy thing1 thing2 thing3
```

I guess it'd be necessary to repeat `host`, `user` and `pass` though.
