### ISSUE TITLE
Error 553 - cant' open that  file. #windows

### ISSUE THREAD

**Issue by machei** [LeanMeanFightingMachine/dploy#84]
Hi guys, 

That's my first time of using dploy on Windows, but also i can't uplaod my files into server. 
Bug: `[Error: Can't open that file: No such file or directory] code: 553`

```
Connecting to dev...
Checking revisions...
Uploading files...
Files that will be uploaded:
[ ? ] app/.htaccess > public_html/inf360/app/.htaccess
```

[screenshot_10](https://cloud.githubusercontent.com/assets/7736131/10705011/0ad1adf8-79db-11e5-973b-19d02f4ee568.png)

My configuration of locations to files is ok.

```
dev:
    scheme: ftp
    host: xxx
    port: 21
    user: xxx
    pass: xxx
    check: true
    path:
        local: "app/"
        remote: "public_html/inf360/app/"
```
