### ISSUE TITLE
Shared settings between environment

### ISSUE THREAD

**Issue by clemorphy** [LeanMeanFightingMachine/dploy#88]
Is there a way to define shared settings that will be used by several environments ?
If the paths in the `exclude` list are the same for all my environments, and if this list is quite long, it may be useful to define it one time for all environments.

Is there currently a way of doing this ?

**Comment by polikin** [comment]
You can create an anchor like this:

```
exclude:
  path: &path [".DS_Store", "aaaa", "bbbb", "node_modules", "cccc", "dddd", "package.json"]

dev:
    scheme: ftp
    host: ftp.xxxx.com
    port: 21
    user: xxx
    pass: xxx
    slots: 6
    path:
        local: /
        remote: public_html/xxxx
    exclude: *path
```

**Anchor names must not contain the [, ], {, } and , characters.**
