### ISSUE TITLE
dploy without GIT

### ISSUE THREAD

**Issue by philmaker1** [LeanMeanFightingMachine/dploy#94]
I really like this tool and I like using it. But, does anyone know if it's possible to deploy from the file system directly instead of git? I know that git is better but I just wanted to ask if it's possible or if there is some other tool available?

Thanks,
Philip

**Comment by philmaker1** [comment]
I might just use gulp-git to commit automatically before right before deploying. But still let me know if dploy could ever support deploying from the local file system.

**Comment by knostradamus** [comment]
+1
I'd love to be able to deploy my build. My source is already tracked in git and I would rather not track the build files.

**Comment by illycz** [comment]
I use git but use this solution for build folder which is in gitignore:

```
dev:
    scheme: ftp
    host: host
    port: 21
    user: user
    pass: pass
    check: true
    path:
        local: dist/
    include:
        "dist/**/*": "/"
```

There is one essential problem, every deploy copy all dist folder :(
